### ISSUE TITLE
AsyncClient eventloop fails if it's spawned in a separate function

### ISSUE THREAD

**Issue by rbino** [bytebeamio/rumqtt#164]
Hi,
I may be missing some subtleties of the language since I'm new to Rust, but I find this behavior strange. Could be similar/related to #103 but I'm not sure.

Basically, this works:
```rust
use rumqttc::{AsyncClient, Event, MqttOptions};

#[tokio::main]
async fn main() {
    let mut mqttoptions = MqttOptions::new("test-rumqttc", "test.mosquitto.org", 1883);
    mqttoptions.set_keep_alive(5);

    let (_client, mut eventloop) = AsyncClient::new(mqttoptions, 10);
    tokio::spawn(async move {
        loop {
            match eventloop.poll().await.unwrap() {
                Event::Incoming(i) => println!("Incoming = {:?}", i),
                Event::Outgoing(o) => println!("Outgoing = {:?}", o),
            }
        }
    });

    loop {}
}
```

This does not:
```rust
use rumqttc::{AsyncClient, Event, MqttOptions};

#[tokio::main]
async fn main() {
    start_stuff();

    loop {}
}

fn start_stuff() {
    let mut mqttoptions = MqttOptions::new("test-rumqttc", "test.mosquitto.org", 1883);
    mqttoptions.set_keep_alive(5);

    let (_client, mut eventloop) = AsyncClient::new(mqttoptions, 10);
    tokio::spawn(async move {
        loop {
            match eventloop.poll().await.unwrap() {
                Event::Incoming(i) => println!("Incoming = {:?}", i),
                Event::Outgoing(o) => println!("Outgoing = {:?}", o),
            }
        }
    });
}
```
 
Failure message:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Cancel', src/main.rs:17:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Backtrace:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Cancel', src/main.rs:17:42
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: core::result::Result<T,E>::unwrap
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15: foobar::start_stuff::{{closure}}
             at src/main.rs:17
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  17: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/core.rs:173
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/loom/std/unsafe_cell.rs:14
  19: tokio::runtime::task::core::Core<T,S>::poll
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/core.rs:158
  20: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/harness.rs:107
  21: core::ops::function::FnOnce::call_once
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:233
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  23: std::panicking::try::do_call
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:348
  24: __rust_try
  25: std::panicking::try
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:325
  26: std::panic::catch_unwind
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  27: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/harness.rs:89
  28: tokio::runtime::task::raw::poll
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/raw.rs:104
  29: tokio::runtime::task::raw::RawTask::poll
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/raw.rs:66
  30: tokio::runtime::task::Notified<S>::run
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/mod.rs:169
  31: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/worker.rs:353
  32: tokio::coop::with_budget::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  33: std::thread::local::LocalKey<T>::try_with
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  34: std::thread::local::LocalKey<T>::with
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  35: tokio::coop::with_budget
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  36: tokio::coop::budget
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  37: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/worker.rs:352
  38: tokio::runtime::thread_pool::worker::Context::run
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/worker.rs:324
  39: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/worker.rs:309
  40: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  41: tokio::runtime::thread_pool::worker::run
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/worker.rs:306
  42: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/worker.rs:285
  43: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/blocking/task.rs:41
  44: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/core.rs:173
  45: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/loom/std/unsafe_cell.rs:14
  46: tokio::runtime::task::core::Core<T,S>::poll
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/core.rs:158
  47: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/harness.rs:107
  48: core::ops::function::FnOnce::call_once
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:233
  49: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:318
  50: std::panicking::try::do_call
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:348
  51: __rust_try
  52: std::panicking::try
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:325
  53: std::panic::catch_unwind
             at /home/rbino/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:394
  54: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/harness.rs:89
  55: tokio::runtime::task::raw::poll
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/raw.rs:104
  56: tokio::runtime::task::raw::RawTask::poll
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/raw.rs:66
  57: tokio::runtime::task::Notified<S>::run
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/task/mod.rs:169
  58: tokio::runtime::blocking::pool::Inner::run
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/blocking/pool.rs:230
  59: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/blocking/pool.rs:210
  60: tokio::runtime::context::enter
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  61: tokio::runtime::handle::Handle::enter
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  62: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/rbino/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/blocking/pool.rs:209
```

I also tried initializing `MqttOptions` outside `start_stuff` and then passing them but the result is the same of the latter (it gets canceled).

**Comment by tekjar** [comment]
That's because you are dropping `_client` handle

**Comment by rbino** [comment]
Got it - I was doing some quick tests before deciding where to put the client and I triggered this. Returning the client from the example above and saving it in `main` effectively fixes the error.

This probably explains the similar issue I had when executing [the example in the documentation](https://docs.rs/rumqttc/0.1.1/rumqttc/#a-simple-asynchronous-publish-and-subscribe) (`client` gets dropped before messages can be received in the loop). 
The example in the `examples` directory works fine.
